version: '3'

services:
  jupyter:
    image: quay.io/jupyter/scipy-notebook:2024-03-14
    container_name: jupyter
    ports:
      - 8888:8888
    volumes:
       - .:/home/jovyan
    environment:
      - .env
    command: >
      /bin/bash -c "
      if [ ! -d /home/jovyan/.git ]; then
          git config --global user.name ${GITHUB_USERNAME} &&
          git config --global user.email ${GITHUB_USEREMAIL} &&
          git config --global credential.helper store &&
          git clone https://${GITHUB_USER}:${GITHUB_TOKEN}${GITHUB_REPO} .
      fi &&
      jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root
      "
